# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f7819887f2907d0d3cbd6644e8fa583a"
name = "minder-cf-app-sf-setup-0-dev"
handle = "minder-cf-app-sf-setup-0-dev"
application_url = "https://dev-tunnel.minder.solutions"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://dev-tunnel.minder.solutions/auth/callback", "https://dev-tunnel.minder.solutions/auth/shopify/callback", "https://dev-tunnel.minder.solutions/api/auth/callback"]

[pos]
embedded = false
