# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6894f22e39e185bef9dada4628044f8a"
name = "cf-sf-app-0-dev"
handle = "cf-sf-app-0-dev"
application_url = "http://localhost"
embedded = true


[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://cf-test-1.minder-solutions.workers.dev/auth" ]

[pos]
embedded = false
