// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSIONS_KV: KVNamespace;
	SCOPES: "write_products";
	DB: D1Database;
}


/*
interface Env {
  DB: D1Database;
  SESSIONS_KV: KVNamespace;
  
  // Add any other bindings your Worker uses
  SHOPIFY_API_KEY: string;
  SHOPIFY_API_SECRET: string;
  SHOPIFY_APP_URL: string;
  SCOPES: string;
  SHOP_CUSTOM_DOMAIN?: string;
}


*/